### ISSUE TITLE
Note about Oracle JDK

### ISSUE THREAD

**Issue by hillar** [martinpaljak/idcrypt#2]
please add Note about Oracle JDK and HowTo

Requires "Unlimited Strength Jurisdiction Policy Files"
Download for Java 1.8: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

unpack

on macosx do

cp * $(/usr/libexec/java_home)/Contents/Home/jre/lib/security/ 

orwhatever...

**Comment by martinpaljak** [comment]
Fixed in 989e22e  and c483a0f  with https://github.com/martinpaljak/cdoc/wiki/UnlimitedCrypto (feel free to improve)

**Comment by martinpaljak** [comment]
As an alternative, it would make sense to use BouncyCastle light interface so that the dependence on the policy would not exist. Extra configuration steps suks.

**Comment by martinpaljak** [comment]
NOTE: add this https://stackoverflow.com/questions/3862800/invalidkeyexception-illegal-key-size

**Comment by martinpaljak** [comment]
Not relevant with modern JDK-s
